// The i18n-ready user-visible string dictionary (WEB-001). Every
// user-visible string flows through t(); the single shipped locale is
// `en`, structured so additional locales slot in without touching
// components.

export type StringKey = keyof typeof en;

export const en = {
  "app.title": "Flauz",
  "app.subtitle": "Your shared agent workspace",
  "banner.connected": "Connected",
  "banner.authenticating": "Signing in",
  "banner.reconnecting": "Reconnecting",
  "banner.failed": "Connection failed",
  "banner.retryNow": "Retry now",
  "banner.nextRetry": "Retrying in {seconds}s…",
  "banner.stateDetail": "What happened: {reason}",
  "banner.session": "Session {id}",
  "signin.title": "Sign in to Flauz",
  "signin.description":
    "Flauz connects to your agent runtime through the local gateway. Sign in with your ChatGPT account or an API key.",
  "signin.chatgpt.button": "Sign in with ChatGPT",
  "signin.chatgpt.pending": "Waiting for you to finish signing in…",
  "signin.chatgpt.open": "Open the authorization page",
  "signin.chatgpt.copied": "Authorization link copied",
  "signin.chatgpt.copy": "Copy authorization link",
  "signin.chatgpt.cancel": "Cancel sign-in",
  "signin.apikey.label": "API key",
  "signin.apikey.button": "Sign in with API key",
  "signin.apikey.hint": "Your key is sent only to your local agent runtime and is never logged or stored by Flauz.",
  "signin.error": "Sign-in failed: {reason}",
  "signin.waitingRuntime": "Connecting to your agent runtime before sign-in…",
  "workspace.title": "Workspace",
  "workspace.sessions.heading": "Sessions",
  "workspace.sessions.description": "Tasks you or your agents are working on, most recent first.",
  "workspace.newTask.button": "Start a new task",
  "workspace.empty.title": "Start your first task",
  "workspace.empty.description":
    "Describe what you want in plain language — no jargon needed. Flauz prepares the environment and agents for you.",
  "workspace.empty.action": "Start a new task",
  "workspace.empty.secondary":
    "Prefer to look around first? The command palette (Ctrl+K) lists everything you can do here.",
  "workspace.loadError": "Could not load your sessions: {reason}",
  "workspace.retryLoad": "Try again",
  "workspace.session.open": "Open session",
  "workspace.session.updated": "Updated {when}",
  "newtask.title": "Start a new task",
  "newtask.description": "Describe your objective in ordinary language. You can refine it after you start.",
  "newtask.objective.label": "What do you want to do?",
  "newtask.objective.placeholder": "For example: Plan the community garden layout for next spring",
  "newtask.start": "Start task",
  "newtask.cancel": "Cancel",
  "newtask.error": "Could not start the task: {reason}",
  "session.back": "Back to workspace",
  "session.connecting": "Connecting to session…",
  "session.connected": "Connected — this session is live",
  "session.nextStep": "Describe the next step, or review what happened below.",
  "session.timeline": "Activity",
  "session.timeline.empty": "Nothing has happened in this session yet. Start by describing your objective.",
  "session.composer.label": "Describe the next step",
  "session.composer.placeholder": "Describe the next step for your agents…",
  "session.composer.send": "Send",
  "session.composer.hint": "Sent to your agent runtime. Use the task controls to pick the model, reference a skill or review artifacts.",
  "session.turn.running": "Working…",
  "session.turn.completed": "Completed",
  "session.turn.failed": "Failed: {reason}",
  "context.button": "Context",
  "context.title": "What your agent knows",
  "context.description": "The current objective and activity your agent is working from.",
  "context.objective": "Objective",
  "context.activity": "Recent activity",
  "context.empty": "No context yet — describe your objective to begin.",
  "context.nextStep": "Full context compilation and pinning arrive with the web capability surfaces.",
  "environments.title": "Environments",
  "approvals.title": "Needs your decision",
  "approvals.command": "Run this command?",
  "approvals.fileChange": "Apply this file change?",
  "approvals.permissions": "Change permissions?",
  "approvals.approve": "Approve",
  "approvals.approveForSession": "Approve for this session",
  "approvals.decline": "Decline",
  "approvals.declined": "Declined",
  "approvals.approved": "Approved",
  "approvals.approvedForSession.record": "Approved for this session",
  "approvals.decided.record": "You decided",
  "approvals.permissions.declined":
    "Declined — permission profile selection arrives with the web capability surfaces.",
  "palette.open": "Command palette",
  "palette.placeholder": "Type a command or search…",
  "palette.empty": "No matching commands.",
  "palette.hint": "↑↓ to move · Enter to run · Esc to close",
  "palette.command.home": "Go to workspace",
  "palette.command.newtask": "Start a new task",
  "palette.command.theme": "Toggle light/dark theme",
  "palette.command.reconnect": "Reconnect now",
  "palette.command.signout": "Sign out",
  "palette.command.shortcuts": "Show keyboard shortcuts",
  "palette.command.environments": "Show this task's environments",
  "palette.command.model": "Choose the model for this task",
  "palette.command.skills": "Show this task's skills",
  "palette.command.collaborators": "Show collaborators and shared decisions",
  "palette.command.artifacts": "Show this task's artifacts",
  "palette.noSession": "Open a task first — the {surface} lives on the task surface.",
  "notice.dismiss": "Dismiss",
  "rail.context": "Context",
  "rail.environments": "Environments",
  "rail.model": "Model",
  "rail.skills": "Skills",
  "rail.collaborators": "Collaborators",
  "rail.artifacts": "Artifacts",
  "gap.title": "Not available from the web yet",
  "gap.what": "What is missing",
  "gap.why": "Why",
  "gap.unlock": "How it unlocks",
  "gap.badge": "Named gap",
  "environments.current.title": "Where this task runs",
  "environments.current.cwd": "Working directory reported by the agent runtime",
  "environments.current.none": "The agent runtime has not reported a working directory for this task.",
  "environments.cwd.label": "Working directory for the next turn",
  "environments.cwd.hint": "Rides the protocol's own per-turn working-directory field — the one environment control the agent runtime's protocol carries today.",
  "environments.cwd.apply": "Apply directory",
  "environments.cwd.clear": "Use the reported directory",
  "environments.cwd.applied": "The next turn will run in {path}",
  "environments.gap.what": "Listing, selecting and connecting remote environments (sandboxes, remote hosts, cloud machines).",
  "environments.gap.why": "The agent runtime's protocol — this client's frozen contract — carries no environment control methods.",
  "environments.gap.unlock": "Environment control needs a protocol extension on the agent runtime; the desktop client is today's reference. Meanwhile, set the working directory above and ask your agent where the work should run.",
  "model.current.title": "This task's model",
  "model.current.model": "Model",
  "model.current.effort": "Reasoning effort",
  "model.current.unreported": "Not reported yet",
  "model.current.provider": "Provider",
  "model.provider.chatgpt": "Your ChatGPT account",
  "model.provider.apikey": "Your API key",
  "model.provider.bedrock": "Amazon Bedrock (managed credentials)",
  "model.provider.none": "Not signed in",
  "model.next.title": "Model for the next turn",
  "model.next.description": "Your choice rides the turn request's own model and effort fields — the same task continues, nothing is lost.",
  "model.next.model.label": "Model id",
  "model.next.model.placeholder": "For example: gpt-5.6-sol",
  "model.next.effort.label": "Reasoning effort",
  "model.next.effort.placeholder": "For example: high",
  "model.next.apply": "Apply to next turn",
  "model.next.clear": "Use the runtime default",
  "model.next.applied": "The next turn will use {model} (effort: {effort}).",
  "model.next.applied.modelOnly": "The next turn will use {model}.",
  "model.gap.what": "Browsing the model catalog (the list of models your account can use).",
  "model.gap.why": "This client's frozen protocol snapshot carries no model-listing method, so Flauz cannot enumerate your models.",
  "model.gap.unlock": "Enter the model id directly above — the choice rides the turn request itself. Regenerating the protocol snapshot from the agent runtime restores the browsable catalog.",
  "skills.reference.title": "Use a skill in this task",
  "skills.reference.description": "Rides the turn request's own skill reference field: name the skill and where it lives.",
  "skills.reference.name": "Skill name",
  "skills.reference.name.placeholder": "For example: seasonal-planting",
  "skills.reference.path": "Skill location",
  "skills.reference.path.placeholder": "For example: /skills/seasonal-planting.md",
  "skills.reference.note": "Optional note for the agent",
  "skills.reference.note.placeholder": "For example: use it for the spring beds",
  "skills.reference.use": "Use skill",
  "skills.reference.pending": "Sending the skill reference…",
  "skills.reference.sent": "Using the skill {name} — watch the timeline.",
  "skills.gap.what": "Listing the skills installed for your agent, and unlocking locked ones.",
  "skills.gap.why": "This client's frozen protocol snapshot carries no skill listing or unlock methods.",
  "skills.gap.unlock": "Reference an installed skill by name above — the turn request carries skill references. When a task hits a capability gap, the failure names what is missing and the recovery path; skill listing and unlocking need the protocol snapshot to carry the skill methods.",
  "collab.shared.title": "Shared decisions",
  "collab.shared.description": "Decisions this task is waiting on — every approval is a named record; Flauz never auto-resolves one.",
  "collab.shared.count": "{count} decisions waiting",
  "collab.shared.none": "No decisions are waiting right now.",
  "collab.shared.show": "Show the decisions",
  "collab.privacy": "Each participant keeps a private context; the shared task state stays canonical.",
  "collab.gap.what": "Seeing collaborators on this workspace and their live presence.",
  "collab.gap.why": "The agent runtime's protocol carries no membership or presence methods, so Flauz cannot list who else is here.",
  "collab.gap.unlock": "Collaboration (owner, admin, contributor and viewer roles, plus live presence) is defined in Flauz's collaboration contract and arrives when the agent runtime's protocol carries it. Until then, shared decisions surface as approval records above.",
  "artifacts.items.title": "What the agent runtime reports",
  "artifacts.items.description": "The items your agent produced for this task, exactly as the runtime reports them.",
  "artifacts.items.empty": "Nothing reported yet. Items appear here as your agent works.",
  "artifacts.items.loading": "Loading what the agent runtime reports…",
  "artifacts.error": "Could not load the reported items: {reason}",
  "artifacts.refresh": "Refresh",
  "artifacts.kind.agentMessage": "Agent message",
  "artifacts.kind.commandExecution": "Command",
  "artifacts.kind.fileChange": "File change",
  "artifacts.kind.other": "Item",
  "artifacts.gap.what": "Documents, spreadsheets and versioned artifacts produced by the task.",
  "artifacts.gap.why": "The agent runtime's protocol carries no artifact, document or sheet methods — only the task items listed above.",
  "artifacts.gap.unlock": "Artifacts need a protocol extension on the agent runtime. Until then, the items above are the honest record of what the task produced.",
  "session.interrupt": "Stop this turn",
  "session.interrupting": "Stopping this turn…",
  "session.interrupt.failed": "Could not stop the turn: {reason}",
  "session.turn.cancelled": "Cancelled: {reason}",
  "session.rail.label": "Task controls",
  "newtask.model.summary": "Model for this task: {model}",
  "newtask.model.default": "Model for this task: the runtime default",
  "newtask.model.change": "Change",
  "newtask.model.label": "Model id",
  "newtask.model.placeholder": "Leave empty to use the runtime default",
  "newtask.model.effort": "Reasoning effort",
  "newtask.model.hide": "Hide",
  "shortcuts.rail.context": "Open the Context panel",
  "shortcuts.rail.environments": "Open the Environments panel",
  "shortcuts.rail.model": "Open the Model panel",
  "shortcuts.rail.skills": "Open the Skills panel",
  "shortcuts.rail.collaborators": "Open the Collaborators panel",
  "shortcuts.rail.artifacts": "Open the Artifacts panel",
  "shortcuts.title": "Keyboard shortcuts",
  "shortcuts.palette": "Command palette",
  "shortcuts.shortcuts": "This shortcut sheet",
  "shortcuts.close": "Close",
  "shortcuts.escape": "Close overlays and restore focus",
  "theme.toggle": "Toggle theme",
  "signout.button": "Sign out",
  "status.dropped": "Some live updates were delayed — reconnecting to refresh",
  "footer.product": "Flauz — the shared agent workspace",
  "footer.gatewayLocal": "Local gateway",
  "footer.gatewayRemote": "Remote gateway",
} as const;

const dictionaries: Record<string, Record<StringKey, string>> = {
  en,
};

export type Translator = (key: StringKey, values?: Record<string, string | number>) => string;

export function createTranslator(locale = "en"): Translator {
  const dictionary = dictionaries[locale] ?? dictionaries["en"];
  return (key, values) => {
    const template = dictionary[key];
    if (values === undefined) {
      return template;
    }
    return template.replace(/\{(\w+)\}/g, (match, name: string) =>
      name in values ? String(values[name]) : match,
    );
  };
}

export function availableLocales(): string[] {
  return Object.keys(dictionaries);
}
